version: "3.7"
services:
  postgres:
    container_name: synthylizer-postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=synthylizer_dev
    ports:
      - "5432:5432"
    volumes:
      - synthylizer-data:/var/lib/postgresql/data

  adminer:
    container_name: synthylizer-adminer
    image: adminer
    ports:
      - 8080:8080

volumes:
  synthylizer-data:
